# Generated by Django 6.0 on 2025-12-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_music_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='music',
            table='music',
        ),
    ]
