# Generated by Django 6.0 on 2025-12-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todo_description_alter_todo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
